/**
     * @description Wrapper to return Website Info From WebService Call
	 * @Author: Maroun Al Hourani
     * @Company: EI-Technologies
	 * @Maroun Al Hourani      Création
     */ 


public class WebsiteInfo {
    public String logoUrl;
    public Integer employees;
    public String foundationDate;
    public String description;
    public String city;
    public String country;
    public String street;
    public String state;
    public String postalCode;

}
